---
deployment:
  tasks:
    - export DEPLOYPATH=/home/lifecircleregula/public_html
    - /bin/cp -r admin $DEPLOYPATH
    - /bin/cp -r assets $DEPLOYPATH
    - /bin/cp -r includes $DEPLOYPATH
    - /bin/cp *.php $DEPLOYPATH
    - /bin/cp .htaccess $DEPLOYPATH
